service: lambda-caleuche

provider:
  name: aws
  runtime: nodejs6.10
  stage: develop
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
      - KMS:Decrypt
      Resource: ${self:custom.kmsSecrets.keyArn}
    - Effect: Allow
      Action:
      - s3:*
      Resource: 'arn:aws:s3:::*'

  environment:
      SECRETS: ${self:custom.kmsSecrets.secrets.SECRETS}

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-kms-secrets
  - serverless-offline

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true
  serverless-kms-secrets:
    secretsFile: kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml
  kmsSecrets: ${file(kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}

functions:
  event_post:
    handler: src/api-v1_handler.event_post
    description: Send a new event
    events:
     - http:
         path: v1/event
         method: post

  event_get:
    handler: src/api-v1_handler.event_get
    description: Retrieve a particular event
    events:
     - http:
         path: v1/event/{id}
         method: get
         request:
            parameters:
              paths:
                id: true

  event_get_all:
    handler: src/api-v1_handler.event_get
    description: Gets all of the events with a limit of 100
    events:
     - http:
         path: v1/event
         method: get


  event_get_paginated:
    handler: src/api-v1_handler.event_get
    description: Gets a paginated subset of the events of the user.
    events:
     - http:
         path: v1/event
         method: get
         integration: lambda
         request:
           template:
             application/json: >
               {
                 "page" : "$input.params(''page'')",
                 "per_page": "$input.params(''per_page'')"
               }
